# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 16:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название категории для новостей. Только строчные латинские буквы. Максимум 30 символов', max_length=30, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Допустимы только строчные латинские символы')], verbose_name='Название')),
                ('description', models.CharField(default=None, help_text='Введите описание данной категории. Максимум 50 символов', max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': ('Категории новостей',),
                'verbose_name_plural': 'Категории новостей',
            },
        ),
        migrations.CreateModel(
            name='InternetTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название для тарифа. Только строчные латинские буквы. Максимум 50 символов', max_length=50, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Допустимы только строчные латинские символы')], verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость для данного тарифа. Максимальное значени 9999.99', max_digits=6, verbose_name='Стоимость')),
                ('link_speed', models.CharField(help_text='Укажите скорость доступа по данному тарифу', max_length=30, verbose_name='Скорость')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(help_text='Укажите заголовок новости. Максимум 30 символов', max_length=50, verbose_name='Заголовок')),
                ('preview_title', models.CharField(help_text='Укажите заголовок для превью новости. Максимум 50 символов', max_length=50, verbose_name='Заголовок для превью')),
                ('image', models.ImageField(help_text='Рекомендуемый размер изображения - 640 на 400 пикселей', upload_to='uploads/images/news_images/', verbose_name='Изображение')),
                ('message', models.CharField(help_text='Тело сообщения для новости. Максимум 500 символов', max_length=500, verbose_name='Сообщение')),
                ('category', models.ForeignKey(help_text='Выберите категорию, в которую попадет данная новость', on_delete=django.db.models.deletion.CASCADE, to='ro_app.InformationCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': ('Новости',),
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='SiteSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название раздела для сайта. Только строчные латинские буквы. Максимум 30 символов', max_length=30, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Допустимы только строчные латинские символы')], verbose_name='Название раздела сайта')),
                ('description', models.CharField(default=None, help_text='Введите описание для данной секции сайта. Максимум 50 символов', max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': ('Разделы сайта',),
                'verbose_name_plural': 'Разделы сайта',
            },
        ),
        migrations.CreateModel(
            name='TarifConnectTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название для данной технологии. Только строчные латинские буквы. Максимум 50 символов', max_length=30, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Допустимы только строчные латинские символы')], verbose_name='Название')),
                ('description', models.CharField(help_text='Укажите описание для данной технологии подключения Интернета', max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': ('Технология подключения Интернета',),
                'verbose_name_plural': 'Технологии подключения Интернета',
            },
        ),
        migrations.CreateModel(
            name='TopPageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите заголовок информера. Максимум 30 символов', max_length=30, verbose_name='Заголовок')),
                ('description', models.CharField(default=None, help_text='Укажите описание информера. Максимум 30 символов', max_length=30, verbose_name='Краткое описание')),
                ('message', models.CharField(help_text='Тело сообщения для информера. Максимум 300 символов', max_length=300, verbose_name='Сообщение')),
                ('image', models.ImageField(help_text='Рекомендуемый размер изображения - 920 на 720 пикселей', upload_to='uploads/images/top_page_info_images/', verbose_name='Изображение')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('link_to_site_section', models.ForeignKey(help_text='Выберите на какой раздел сайта будет ссылаться информер', on_delete=django.db.models.deletion.CASCADE, to='ro_app.SiteSections', verbose_name='Ссылка на раздел сайта')),
            ],
            options={
                'verbose_name': ('Заметка в заголовке страницы',),
                'verbose_name_plural': 'Заметка в заголовке страницы',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='link_to_site_section',
            field=models.ForeignKey(help_text='Выберите на какой раздел сайта будет ссылаться данная новость', on_delete=django.db.models.deletion.CASCADE, to='ro_app.SiteSections', verbose_name='Ссылка на раздел сайта'),
        ),
        migrations.AddField(
            model_name='internettarif',
            name='type_connect',
            field=models.ForeignKey(default=None, help_text='Выберите технологию подключения для данногот тарифа', on_delete=django.db.models.deletion.CASCADE, to='ro_app.TarifConnectTechnology', verbose_name='Тип подключения'),
        ),
    ]
