# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название для телефонного направления (страну, регион, населенный пункт)', max_length=100, verbose_name='Название направления')),
                ('phone_code', models.IntegerField(help_text='Укажите код для данного телефонного направления', verbose_name='Код направления')),
                ('first_price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость в будние дневные дни для данного тарифа. Максимальное значени 9999.99', max_digits=6, verbose_name='Стоимость в будние дни')),
                ('second_price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость в вечернее и ночное время для данного тарифа. Максимальное значени 9999.99', max_digits=6, verbose_name='Стоимость в вечерние часы')),
                ('third_price', models.DecimalField(decimal_places=2, help_text='Укажите стоимость в выходные и праздничные дни для данного тарифа. Максимальное значени 9999.99', max_digits=6, verbose_name='Стоимость в выходные')),
            ],
            options={
                'verbose_name': ('МГ/МН тариф',),
                'verbose_name_plural': 'МГ/МН тарифы',
            },
        ),
        migrations.AlterModelOptions(
            name='informationcategory',
            options={'verbose_name': ('Категория новостей',), 'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterModelOptions(
            name='internettarif',
            options={'verbose_name': ('Тариф Интренет',), 'verbose_name_plural': 'Тарифы Интернет'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': ('Новость',), 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='sitesections',
            options={'verbose_name': ('Раздел сайта',), 'verbose_name_plural': 'Разделы сайта'},
        ),
        migrations.AlterModelOptions(
            name='toppageinformation',
            options={'verbose_name': ('Заметка в заголовке страницы',), 'verbose_name_plural': 'Заметки в заголовке страницы'},
        ),
    ]
