# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0003_auto_20170727_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='default_image',
        ),
        migrations.AddField(
            model_name='notice',
            name='use_default_image',
            field=models.BooleanField(default=None, help_text='Укажите использовать ли изображение по умолчанию исходя из категории новости', verbose_name='Изображение по умолчанию'),
        ),
    ]
