# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0004_auto_20170728_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description_for_link_to_site_section',
            field=models.CharField(default=None, help_text='Укажите описание для ссылки на соответствующий раздел сайта', max_length=50, verbose_name='Описание для ссылки на раздел сайта'),
        ),
    ]
