# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 17:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0006_auto_20170728_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifconnecttechnology',
            options={'verbose_name': ('Технология тарифа',), 'verbose_name_plural': 'Технологии тарифов'},
        ),
        migrations.AddField(
            model_name='internettarif',
            name='type',
            field=models.CharField(choices=[('ethernet-tarifs', 'Тариф по технологии Ethernet'), ('adsl-tarifs', 'Тариф по технологии ADSL')], default=None, help_text='Выберите тип подключенияьф данного тарифа', max_length=1, verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='tarifconnecttechnology',
            name='description',
            field=models.CharField(help_text='Укажите описание для данной категории тарифов', max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tarifconnecttechnology',
            name='name',
            field=models.CharField(help_text='Укажите название для данной категории тарифов. Только строчные латинские буквы. Максимум 50 символов', max_length=30, validators=[django.core.validators.RegexValidator('^[a-z]*$', 'Допустимы только строчные латинские символы')], verbose_name='Название'),
        ),
    ]
