# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0007_auto_20170729_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internettarif',
            name='type_connect',
        ),
    ]
