# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0008_remove_internettarif_type_connect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TarifConnectTechnology',
        ),
    ]
