# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0009_delete_tarifconnecttechnology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите коректный электронный адрес для подписки', max_length=100, verbose_name='E-mail адрес')),
            ],
            options={
                'verbose_name': ('Электронный адрес для подписки',),
                'verbose_name_plural': 'Список электронных адресов для подписки',
            },
        ),
    ]
