# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0010_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Общие вопросы', 'Общие вопросы'), ('Подключить услугу', 'Подключить услугу'), ('Технические неполадки', 'Технические неполадки')], help_text='Укажите категорию обращения пользователя', max_length=100, verbose_name='Категория обращения')),
                ('user_name', models.CharField(help_text='Укажите как обращаться к пользователю', max_length=150, verbose_name='Имя пользователя')),
                ('user_phone', models.IntegerField(help_text='Укажите контактный телефон пользователя', verbose_name='Контактный телефон пользователя')),
                ('message', models.CharField(help_text='Введите текст сообщения пользователя', max_length=500, verbose_name='Сообщение пользователя')),
                ('creation_date', models.DateTimeField(help_text='Дата создания обращения', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': ('Обращение от пользователя',),
                'verbose_name_plural': 'Все обращения от пользователей',
            },
        ),
        migrations.AlterField(
            model_name='informationcategory',
            name='image',
            field=models.ImageField(default=None, help_text='Выберите изображение для категории, которое будет применяться ко  всем новостям категории без указания изображения .Рекомендуемый размер изображения - 640 на 400 пикселей', upload_to='ro_app/content/images/default_category_news_images/', verbose_name='Изображение по умолчанию'),
        ),
    ]
