# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0013_auto_20170807_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internettarif',
            name='title',
            field=models.CharField(help_text='Укажите название для тарифа. Только строчные латинские буквы. Максимум 50 символов', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internettarif',
            name='type',
            field=models.CharField(choices=[('ethernet-tarifs', 'Тариф по технологии Ethernet'), ('adsl-tarifs', 'Тариф по технологии ADSL')], default=None, help_text='Выберите тип подключенияьф данного тарифа', max_length=100, verbose_name='Тип подключения'),
        ),
    ]
