# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0016_auto_20170807_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Укажите электронный адрес на который следует отправлять уведомления', max_length=100, verbose_name='E-mail адрес')),
                ('description', models.CharField(help_text='Прокомментируйте принадлежность данного E-mail адреса', max_length=300, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': ('Электроный адрес для уведомлений',),
                'verbose_name_plural': 'Список электроных адресов для уведомлений',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, help_text='Дата создания обращения', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Рекомендуемый размер изображения - 640 на 400 пикселей (иначе изображение будет масштабироваться автоматически с возможной потерей качества).', null=True, upload_to='images/news_images/', verbose_name='Изображение'),
        ),
    ]
