# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-24 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ro_app', '0018_auto_20171220_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTarifFromCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=None, default=None, help_text="Импорт возможен только из CSV файла с разделителем ';'.Также перед импортом обязательно проверяйте структуру CSX файла на соответствие формату - 'Название направления;Код;Стоимость в будни;Стоимость в вечернее время;Стоимость в праздники'. В случае несоответствия формату импорт не будет выполнен либо будет выполнен с ошибками. ", upload_to='import/phone_tarifs/', verbose_name='Файл импорта МГ/МН тарифов')),
            ],
            options={
                'verbose_name': 'Импорт МГ/МН тарифов из внешнего CSV файла',
                'verbose_name_plural': 'Импорт МГ/МН тарифов из внешнего CSV файла',
            },
        ),
    ]
